sensor:
- platform: derivative
  name: "Waschmaschine Power"
  unique_id: waschmaschine_power
  source: sensor.waschmaschine_energieverbrauch # Hier deinen exakten Entitäts-Namen prüfen
  unit_time: h
  unit: W
  time_window: "00:05:00"