binary_sensor: 
  - trigger:
      - platform: state
        entity_id: "{{ this.entity_id }}"
    unique_id: 95:6C:64:58:5C:22
    name: 95:6C:64:58:5C:22
    state: "off"
    attributes:
      friendly_name: Merjas Türöffner
      device_key: !secret merja_door_key
      device_id: "0x8d, 0x6f, 0xf1, 0x3f, 0x5b, 0x95, 0x05, 0x20, 0xf4, 0xd0"
      cutoff_rssi: -99
      allowed_times: |
        sunday:
        - "00:00:00-23:59:59"
        tuesday:
        - "00:00:00-23:59:59"
        thursday:
        - "00:00:00-23:59:59"
        saturday:
        - "00:00:00-23:59:59"
        friday:
        - "00:00:00-23:59:59"
        monday:
        - "00:00:00-23:59:59"
        wednesday:
        - "00:00:00-23:59:59"
      restart_count: "{{ this.attributes.restart_count or '0' }}"
      last_seen_local: "{{ this.attributes.last_seen_local or '0' }}"
      last_seen: "{{ this.attributes.last_seen or '0' }}"
  - trigger:
      - platform: time_pattern
        # This will update every night
        hours: 0
        minutes: 0
    unique_id: 65:74:BB:ED:42:2D
    name: 65:74:BB:ED:42:2D
    state: "off"
    attributes:
      friendly_name: Fabians Türöffner
      device_key: !secret fabian_door_key
      device_id: "0x14, 0xf3, 0x60, 0x71, 0x19, 0xba, 0x09, 0x95, 0x85, 0x48"
      cutoff_rssi: -99
      allowed_times: |
        sunday:
        - "00:00:00-23:59:59"
        tuesday:
        - "00:00:00-23:59:59"
        thursday:
        - "00:00:00-23:59:59"
        saturday:
        - "00:00:00-23:59:59"
        friday:
        - "00:00:00-23:59:59"
        monday:
        - "00:00:00-23:59:59"
        wednesday:
        - "00:00:00-23:59:59"
      restart_count: "{{ this.attributes.restart_count or '0' }}"
      last_seen_local: "{{ this.attributes.last_seen_local or '0' }}"
      last_seen: "{{ this.attributes.last_seen or '0' }}"