binary_sensor:
  - unique_id: 65:74:BB:ED:42:2D
    name: Fabians Türöffner
    state: "off"
    attributes:
      device_key: !secret fabian_door_key
      device_id: "0x14, 0xf3, 0x60, 0x71, 0x19, 0xba, 0x09, 0x95, 0x85, 0x48"
      cutoff_rssi: -99
      allowed_times: |
        sunday:
        - "00:00:00-23:59:59"
        tuesday:
        - "00:00:00-23:59:59"
        thursday:
        - "00:00:00-23:59:59"
        saturday:
        - "00:00:00-23:59:59"
        friday:
        - "00:00:00-23:59:59"
        monday:
        - "00:00:00-23:59:59"
        wednesday:
        - "00:00:00-23:59:59"