binary_sensor:
  - unique_id: 65:74:BB:ED:42:2D
    name: 65:74:BB:ED:42:2D
    state: "off"
    attributes:
      friendly_name: Fabians Türöffner
      device_key: TEST_KEY
      device_id: TEST_ID
      cutoff_rssi: -99
      allowed_times: |
        sunday:
        - "00:00:00-23:59:59"
        tuesday:
        - "00:00:00-23:59:59"
        thursday:
        - "00:00:00-23:59:59"
        saturday:
        - "00:00:00-23:59:59"
        friday:
        - "00:00:00-23:59:59"
        monday:
        - "00:00:00-23:59:59"
        wednesday:
        - "00:00:00-23:59:59"