- alias: [[ room ]] Heizung Sicherheitsschalter
  id: heating_security_switch_[[ room ]]
  description: ""
  mode: single
  triggers:
    - trigger: numeric_state
      entity_id:
        - sensor.security_temperature_[[ room ]]_max
      above: 23.5
  conditions: []
  actions:
    - action: climate.set_hvac_mode
      metadata: {}
      target:
        entity_id: climate.climate_room_[[ room ]]
      data:
        hvac_mode: "off"
