esphome:
  name: airquality-sensor
  friendly_name: AirQuality Sensor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: sensair_background_calibrate
      then:
        - senseair.background_calibration: senseair_s
    - service: sensair_background_calibration_result
      then:
        - senseair.background_calibration_result: senseair_s
  encryption:
    key: "QrmiQUoSy8NxQ9/3c6hnKXBYRWbVQ5/umMd0lKUernM="

ota:
  - platform: esphome
    password: "199482cdf70f0d367b0290587a56a516"

switch:
  - platform: safe_mode
    name: "Flash Mode (Safe Mode)"
  - platform: gpio
    pin: 
      number: D7
    inverted: no
    id: pms_set

interval:
  - interval: 10s
    then:
      - switch.turn_on: pms_set
      - delay: 3s
      - switch.turn_off: pms_set

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Airquality-Sensor"
    password: "ar88ROG7FjT3"

captive_portal:

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart3
    
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart4
  
sensor:
  - platform: pmsx003
    type: PMS5003T
    uart_id: uart3
    pm_2_5:
      id: pm25
      name: "Particulate Matter <2.5µm Concentration"
  - platform: senseair
    id: senseair_s
    uart_id: uart4
    co2:
      id: co2
      name: "SenseAir CO2 Value"
    update_interval: 10s