triggers:
- trigger: time_pattern
  minutes: /5
sensor:
- name: "C_kWh_per_K_rolling"
  unit_of_measurement: "kWh/K"
  state: >
    {{ states('sensor.c_building') | float(10.2) }}
- name: "C Building"
  unique_id: c_building
  unit_of_measurement: "kWh/K"
  attributes:
    duration_h: >
      {{ (as_timestamp(states.sensor.inside_temp_mean_now.last_changed) - as_timestamp(states('input_datetime.cooldown_start_time'))) / 3600 }}
    temp_drop: >
      {{ states('input_number.cooldown_start_temp') - states('sensor.inside_temp_mean_now') | float(0) }}
    avg_delta_t: >
      {{ states('sensor.deltaT_24h') | float(0) }}
    energy_lost: >
      {{ states('input_number.cooldown_start_h_wind') * states('sensor.deltaT_24h') * (as_timestamp(states.sensor.inside_temp_mean_now.last_changed) - as_timestamp(states('input_datetime.cooldown_start_time'))) / 3600 }}
    energy_lost_per_temp_drop: >
      {{ states('input_number.cooldown_start_h_wind') * states('sensor.deltaT_24h') * (as_timestamp(states.sensor.inside_temp_mean_now.last_changed) - as_timestamp(states('input_datetime.cooldown_start_time'))) / 3600 / (states('input_number.cooldown_start_temp') - states('sensor.inside_temp_mean_now') | float(0)) }}
  state: >
    {% set invalid = ['unknown','unavailable','none','', None] %}
    {% set t_start = states('input_number.cooldown_start_temp') | float(0) %}
    {% set t_now = states('sensor.inside_temp_mean_now') | float(0) %}
    {% set h_start = states('input_number.cooldown_start_h_wind') | float(0) %}
    {% set start_time = states('input_datetime.cooldown_start_time') %}
    {% set start_ts = as_timestamp(start_time) %}
    
    {# Der Zeitstempel, wann die AKTUELL angezeigte Temperatur erreicht wurde #}
    {% set last_changed_ts = as_timestamp(states.sensor.inside_temp_mean_now.last_changed) %}

    {% if t_start > 0 and start_ts > 100000 %}
      {% set duration_h = (last_changed_ts - start_ts) / 3600 %}
      {% set temp_drop = t_start - t_now %}
      {% set avg_delta_t = states('sensor.deltaT_24h') | float(0) %}
      
      {# Wir brauchen mindestens 3h Abkühlung und 0.2K Drop für ein sauberes Ergebnis #}
      {% if duration_h > 3 and temp_drop > 0.15 %}
        {% set energy_lost = h_start * avg_delta_t * duration_h %}
        {{ (energy_lost / temp_drop) | round(2) }}
      {% else %}
        {% set prev = this.state %}
        {% if prev not in invalid %}
          {{ prev }}
        {% else %}
          unknown
        {% endif %}
      {% endif %}
    {% else %}
      {% set prev = this.state %}
      {% if prev not in invalid %}
        {{ prev }}
      {% else %}
        unknown
      {% endif %}
    {% endif %}
