sensor:
- name: c_eff_day
  unit_of_measurement: "kWh/K"
  state: >
    {% set E = states('sensor.stored_energy_day')|float(0) %}
    {% set dT = states('sensor.temp_gain_day')|float(0) %}
    {% if dT > 0.15 and E > 0 %}
      {{ (E / dT) | round(2) }}
    {% else %}
      {{ iif(false,0,0) }}
    {% endif %}