sensor:
- name: c_eff_day
  unit_of_measurement: "kWh/K"
  state: >
    {# Use rolling 24h sensors instead of daily-reset utility meters #}
    {% set invalid = ['unknown','unavailable','none','', None] %}
    {% set E_raw = states('sensor.stored_energy_24h') %}
    {% set dT_raw = states('sensor.temp_gain_24h') %}
    
    {# Handle unavailable states #}
    {% if E_raw in invalid or dT_raw in invalid %}
      {% set prev = this.state %}
      {% if prev not in invalid %}
        {{ prev }}
      {% else %}
        unknown
      {% endif %}
    {% else %}
      {% set E = E_raw | float(0) %}
      {% set dT = dT_raw | float(0) %}
      
      {# Validate reasonable limits to filter outliers from data gaps #}
      {# Max stored energy in 24h: 100 kWh (4+ kW average, very high but possible) #}
      {# Max temp gain in 24h: 5K (huge temperature rise) #}
      {% if E > 100 or dT > 5 or E < 0 or dT < 0 %}
        {# Unrealistic values - likely due to data gap, use previous value #}
        {% set prev = this.state %}
        {% if prev not in invalid %}
          {{ prev }}
        {% else %}
          unknown
        {% endif %}
      {% elif dT > 0.15 and E > 0 %}
        {% set c_eff = E / dT %}
        {# Cap c_eff at reasonable maximum (200 kWh/K is very high) #}
        {% if c_eff > 200 %}
          {% set prev = this.state %}
          {% if prev not in invalid and prev | float(0) <= 200 %}
            {{ prev }}
          {% else %}
            unknown
          {% endif %}
        {% else %}
          {{ c_eff | round(2) }}
        {% endif %}
      {% else %}
        {# Not enough data - keep previous or return unknown #}
        {% set prev = this.state %}
        {% if prev not in invalid %}
          {{ prev }}
        {% else %}
          unknown
        {% endif %}
      {% endif %}
    {% endif %}