sensor:
- name: c_eff_last_night
  unit_of_measurement: "kWh/K"
  state: >
    {% set E  = states('sensor.heating_energy_00_06_today_sql')|float(0) %}
    {% set L  = states('sensor.heat_loss_00_06_kwh')|float(0) %}
    {% set dT = states('sensor.deltaT_preheat_00_06')|float(0) %}
    {% set Es = max(E - L, 0) %}
    {% if dT > 0.15 and Es > 0 %}
      {{ (Es / dT) | round(2) }}
    {% else %} {{ iif(false,0,0) }} {% endif %}