sensor:
  - name: c_eff_day_debug
    state: >
      {% set E = states('sensor.stored_energy_day')|float(0) %}
      {% set dT = states('sensor.temp_gain_day')|float(0) %}
      {% set heating_power = states('sensor.heating_power_rate')|float(0) %}
      {% set H = states('sensor.H_kW_per_K_effective')|float(0) %}
      {% set Ti = states('sensor.inside_temp_mean_now')|float(0) %}
      {% set To = states('sensor.outside_temperature')|float(0) %}
      {% set heat_loss_power = H * max(Ti - To, 0) %}
      {% set net_power = states('sensor.net_power_pos')|float(0) %}
      {% set stored_total = states('sensor.stored_energy_total')|float(0) %}
      {{ dict(
        stored_energy_day_kWh=E,
        temp_gain_day_K=dT,
        c_eff_kWh_per_K=(E/dT if dT>0.15 else 0),
        heating_power_kW=heating_power,
        heat_loss_power_kW=heat_loss_power,
        net_power_kW=net_power,
        stored_energy_total_kWh=stored_total,
        H_effective_kW_per_K=H,
        Ti_C=Ti,
        To_C=To
      )|tojson }}
