sensor:
- name: temp_rate_pos
  unit_of_measurement: "K/h"
  state_class: measurement
  state: >
    {% set r = states('sensor.indoor_temp_rate')|float(0) %}
    {{ max(r, 0) | round(4) }}
- name: net_power_pos
  unit_of_measurement: "kW"
  state_class: measurement
  device_class: power
  state: >
    {# Instantaneous heating power (derivative of total energy) #}
    {% set heating_power = states('sensor.heating_power_rate')|float(0) %}
    {# Instantaneous heat loss power = H × ΔT #}
    {% set H = states('sensor.H_kW_per_K_effective')|float(0) %}
    {% set Ti = states('sensor.inside_temp_mean_now')|float(0) %}
    {% set To = states('sensor.outside_temperature')|float(0) %}
    {% set heat_loss_power = H * max(Ti - To, 0) %}
    {# Net power going into storage (only positive) #}
    {{ max(heating_power - heat_loss_power, 0) | round(4) }}