sensor:
- name: deltaT
  unit_of_measurement: "K"
  state: >
    {% set ti = states('sensor.inside_temp_mean_now')|float(none) %}
    {% set to = states('sensor.outside_temperature')|float(none) %}
    {% if ti is not none and to is not none %}
      {{ max(ti - to, 0) | round(2) }}
    {% else %} unknown {% endif %}
  availability: >
    {{ states('sensor.inside_temp_mean_now') not in ['unknown','unavailable','none']
       and states('sensor.outside_temperature') not in ['unknown','unavailable','none'] }}