sensor:
- name: h_k_w_per_k_raw
  unit_of_measurement: "kW/K"
  state: >
    {% set E = states('sensor.heating_energy_24h')|float(0) %}
    {% set dT = states('sensor.deltaT_24h')|float(0) %}
    {% if E > 0 and dT > 0.5 %}
      {{ (E / (dT * 24.0)) | round(3) }}
    {% else %}
      {{ states('sensor.h_k_w_per_k_raw') if states('sensor.h_k_w_per_k_raw') not in ['unknown','unavailable'] else 0 }}
    {% endif %}
  availability: >
    {{ states('sensor.heating_energy_24h') not in ['unknown','unavailable','none']
       and states('sensor.deltaT_24h')|float(0) > 0.5 }}
