sensor:
- name: deltaT_24h_actual_sql
  unit_of_measurement: "K"
  state: >
    {% set ti = states('sensor.inside_temp_mean_24h_sql')|float(0) %}
    {% set to = states('sensor.outside_temp_mean_24h_sql')|float(0) %}
    {% set dt = ti - to %}
    {{ (dt if dt > 0 else 0) | round(2) }}
  availability: >
    {{ states('sensor.inside_temp_mean_24h_sql') not in ['unknown','unavailable','none']
       and states('sensor.outside_temp_mean_24h_sql') not in ['unknown','unavailable','none'] }}
- name: h_k_w_per_k_raw
  unit_of_measurement: "kW/K"
  state: >
    {% set E = states('sensor.heating_energy_24h_sql')|float(0) %}
    {% set dT = states('sensor.deltaT_24h_actual_sql')|float(0) %}
    {% if E > 0 and dT > 0.5 %}
      {{ (E / (dT * 24.0)) | round(3) }}
    {% else %}
      {{ states('sensor.h_k_w_per_k_raw') if states('sensor.h_k_w_per_k_raw') not in ['unknown','unavailable'] else 0 }}
    {% endif %}
  availability: >
    {{ states('sensor.heating_energy_24h_sql') not in ['unknown','unavailable','none']
       and states('sensor.deltaT_24h_actual_sql')|float(0) > 0.5 }}
