sensor:
  - name: deltaT_preheat_00_06
    unit_of_measurement: "K"
    state: >
      {% set t0 = states('input_number.inside_temp_at_00')|float(none) %}
      {% set t1 = states('input_number.inside_temp_at_06')|float(none) %}
      {% set ts0 = states('input_datetime.inside_temp_at_00_ts') %}
      {% set ts1 = states('input_datetime.inside_temp_at_06_ts') %}
      {% if t0 is not none and t1 is not none and ts0 not in ['unknown','unavailable','none'] and ts1 not in ['unknown','unavailable','none'] %}
        {% set d0 = as_datetime(ts0).date() %}
        {% set d1 = as_datetime(ts1).date() %}
        {% if d0 == now().date() and d1 == now().date() %}
          {{ max(t1 - t0, 0) | round(2) }}
        {% else %}
          {{ none }}
        {% endif %}
      {% else %}
        {{ none }}
      {% endif %}