sensor:
- name: deltaT_preheat_00_06
  unit_of_measurement: "K"
  state: >
    {% set t0 = states('input_number.inside_temp_at_00')|float(none) %}
    {% set t1 = states('input_number.inside_temp_at_06')|float(none) %}
    {% if t0 is not none and t1 is not none %}
      {{ (t1 - t0) | round(2) }}
    {% else %}
      {{ none }}
    {% endif %}