sensor:
- name: duty_global_weighted_last_30m
  unit_of_measurement: "%"
  state: >
    {# Liste: (Sensor-Name, kW) #}
    {% set pairs = [
      ('sensor.duty_bad_last_30m',          1.219),
      ('sensor.duty_schlafzimmer_last_30m', 1.955),
      ('sensor.duty_kueche_last_30m',       2.174),
      ('sensor.duty_flur_last_30m',         2.484),
      ('sensor.duty_speisekammer_last_30m', 0.518),
      ('sensor.duty_wohnzimmer_last_30m',   2.691),
      ('sensor.duty_buero_merja_last_30m',  3.163),
      ('sensor.duty_buero_fabian_last_30m', 0.978),
    ] %}
    {% set ns = namespace(sw=0.0, sp=0.0) %}
    {% for name, p in pairs %}
      {# states(name) kann 'unknown'/'unavailable' sein → float(0) #}
      {% set d = states(name) | float(0) %}
      {% set ns.sw = ns.sw + (d * p) %}
      {% set ns.sp = ns.sp + p %}
    {% endfor %}
    {% if ns.sp > 0 %}
      {{ (100.0 * ns.sw / ns.sp) | round(1) }}
    {% else %}
      0
    {% endif %}
- name: duty_global_weighted_last_60m
  unit_of_measurement: "%"
  state: >
    {% set pairs = [
      ('sensor.duty_bad_last_60m',          1.219),
      ('sensor.duty_schlafzimmer_last_60m', 1.955),
      ('sensor.duty_kueche_last_60m',       2.174),
      ('sensor.duty_flur_last_60m',         2.484),
      ('sensor.duty_speisekammer_last_60m', 0.518),
      ('sensor.duty_wohnzimmer_last_60m',   2.691),
      ('sensor.duty_buero_merja_last_60m',  3.163),
      ('sensor.duty_buero_fabian_last_60m', 0.978),
    ] %}
    {% set ns = namespace(sw=0.0, sp=0.0) %}
    {% for name, p in pairs %}
      {% set d = states(name) | float(0) %}
      {% set ns.sw = ns.sw + (d * p) %}
      {% set ns.sp = ns.sp + p %}
    {% endfor %}
    {% if ns.sp > 0 %}
      {{ (100.0 * ns.sw / ns.sp) | round(1) }}
    {% else %}
      0
    {% endif %}