sensor:
- name: duty_global_weighted_last_30m
  unit_of_measurement: "%"
  state: >
    {# Liste: (Sensor-Name, kW) #}
    {% set pairs = [
      ('sensor.duty_bad_last_30m',          1.219),
      ('sensor.duty_schlafzimmer_last_30m', 1.955),
      ('sensor.duty_kueche_last_30m',       2.174),
      ('sensor.duty_flur_last_30m',         2.484),
      ('sensor.duty_speisekammer_last_30m', 0.518),
      ('sensor.duty_wohnzimmer_last_30m',   2.691),
      ('sensor.duty_buero_merja_last_30m',  3.163),
      ('sensor.duty_buero_fabian_last_30m', 0.978),
    ] %}
    {% set ns = namespace(sw=0.0, sp=0.0) %}
    {% for name, p in pairs %}
      {% set raw = states(name) | float(0) %}
      {# auto-scale: 0–100% -> 0–1 ; 0–1 bleibt 0–1 #}
      {% set d = (raw / 100.0) if raw > 1 else raw %}
      {% set d = 0 if d < 0 else (1 if d > 1 else d) %}
      {% set ns.sw = ns.sw + d * p %}
      {% set ns.sp = ns.sp + p %}
    {% endfor %}
    {% if ns.sp > 0 %}
      {{ (ns.sw / ns.sp * 100) | round(2) }}
    {% else %} 0 {% endif %}
- name: duty_global_weighted_last_60m
  unit_of_measurement: "%"
  state: >
    {% set pairs = [
      ('sensor.duty_bad_last_60m',          1.219),
      ('sensor.duty_schlafzimmer_last_60m', 1.955),
      ('sensor.duty_kueche_last_60m',       2.174),
      ('sensor.duty_flur_last_60m',         2.484),
      ('sensor.duty_speisekammer_last_60m', 0.518),
      ('sensor.duty_wohnzimmer_last_60m',   2.691),
      ('sensor.duty_buero_merja_last_60m',  3.163),
      ('sensor.duty_buero_fabian_last_60m', 0.978),
    ] %}
    {% set ns = namespace(sw=0.0, sp=0.0) %}
    {% for name, p in pairs %}
      {% set raw = states(name) | float(0) %}
      {# auto-scale: 0–100% -> 0–1 ; 0–1 bleibt 0–1 #}
      {% set d = (raw / 100.0) if raw > 1 else raw %}
      {% set d = 0 if d < 0 else (1 if d > 1 else d) %}
      {% set ns.sw = ns.sw + d * p %}
      {% set ns.sp = ns.sp + p %}
    {% endfor %}
    {% if ns.sp > 0 %}
      {{ (ns.sw / ns.sp * 100) | round(2) }}
    {% else %} 0 {% endif %}