sensor:
  - name: H_kW_per_K_effective
    unit_of_measurement: "kW/K"
    state: >
      {# 1. BASIS-TRANSMISSION (Hülle) #}
      {% set H_basis = states('input_number.h_kw_per_k')|float(0.074) %}
      
      {# 2. WIND-INFILTRATION (Sherman-Grimsrud Modell mit Abschirmfaktor) #}
      {% set v_ms = states('sensor.wind_speed_ms')|float(0) %}
      {% set n50 = 0.95 %}
      {% set volumen = 388 %}
      {% set n_real = n50 * (v_ms / 10) %} 
      {# 0.1 Faktor für die stark geschützte Lage (Kessel-Lage) #}
      {% set H_wind_zuschlag = (volumen * n_real * 0.34 / 1000) * 0.1 %}

      {# 3. HRV-LÜFTUNGSVERLUST (Stiebel Eltron LWZ 180) #}
      {# Hier greifen wir auf die eingestellten 120m³/h und 85% WRG zurück #}
      {% set flow = states('input_number.hrv_flow_rate') | float(120) %}
      {% set wrg = states('input_number.hrv_wrg_efficiency') | float(0.85) %}
      {# Formel: Volumenstrom * Wärmekapazität * (1 - Wirkungsgrad) #}
      {% set H_hrv = (flow * 0.34 * (1 - wrg)) / 1000 %}

      {# GESAMT-H (Hülle + Wind + HRV) #}
      {{ (H_basis + H_wind_zuschlag + H_hrv) | round(4) }}
    availability: >
      {{ states('input_number.h_kw_per_k') not in ['unknown','unavailable','none']
         and states('sensor.wind_speed_now_kmh') not in ['unknown','unavailable','none'] }}