sensor:
  - name: H_kW_per_K_effective
    unit_of_measurement: "kW/K"
    state: >
      {% set H = states('sensor.H_kW_per_K_rolling')|float(0.055) %}
      {% set v_kmh = states('sensor.wind_speed_mean_24h')|float(0) %}
      {% set v_ms = v_kmh / 3.6 %}
      {% set boost = 1 + 0.1 * max(0, v_ms - 3) %}
      {{ (H * boost) | round(3) }}
    availability: >
      {{ states('sensor.H_kW_per_K_rolling') not in ['unknown','unavailable','none']
         and states('sensor.wind_speed_mean_24h') not in ['unknown','unavailable','none'] }}
