sensor:
  - name: H_kW_per_K_effective
    unit_of_measurement: "kW/K"
    state: >
      {% set H_basis = states('sensor.H_kW_per_K_rolling')|float(0.074) %}
      {% set v_kmh = states('sensor.wind_speed_mean_24h')|float(0) %}
      {% set v_ms = v_kmh / 3.6 %}
      {% set n50 = 0.95 %}
      {% set volumen = 388 %}

      {# Physikalischer Luftwechsel n_v nach dem Sherman-Grimsrud Modell (vereinfacht) #}
      {# Wir nutzen einen Realitätsfaktor von ca. 0.04 bis 0.07 für den n50-Wert #}
      {% set n_real = n50 * (v_ms / 10) %} 

      {# Berechnung des zusätzlichen Wind-H-Werts in kW/K #}
      {% set H_wind_zuschlag = (volumen * n_real * 0.34 / 1000) * 0.1 %}

      {# Gesamtwert #}
      {{ (H_basis + H_wind_zuschlag) | round(3) }}
    availability: >
      {{ states('sensor.H_kW_per_K_rolling') not in ['unknown','unavailable','none']
         and states('sensor.wind_speed_mean_24h') not in ['unknown','unavailable','none'] }}
