sensor:
  - name: H_kW_per_K_effective
    unit_of_measurement: "kW/K"
    state_class: measurement
    state: >
      {# 1. BASIS-TRANSMISSION (Hülle + Wärmebrücken) #}
      {# Wir nutzen hier 0.068 (68 W/K) als statischen Anker inkl. Wärmebrücken #}
      {% set H_basis = states('input_number.h_kw_per_k')|float(0.068) %}
      
      {# 2. WIND-INFILTRATION #}
      {% set v_ms = states('sensor.wind_speed_ms')|float(0) %}
      {% set n50 = 0.9 %}
      {% set volumen = 122.65 * 2.75 %} # 122.65m² * 2.75m = 336.25m³
      {# Wir berechnen den Wind-Einfluss basierend auf der Druckdifferenz-Logik #}
      {# n_inf = n50 * e (Abschirmfaktor). Bei 14km/h war e ca. 0.075 #}
      {# Faktor 0.02 entspricht einem mäßig abgeschirmten Gebäude #}
      {% set n_wind = n50 * (v_ms * 0.02) %}
      {% set H_wind_zuschlag = (volumen * n_wind * 0.34) / 1000 %}

      {# 3. HRV-LÜFTUNGSVERLUST (LWZ 180) #}
      {% set flow = states('input_number.hrv_flow_rate') | float(160) %}
      {% set wrg = states('input_number.hrv_wrg_efficiency') | float(0.90) %}
      {% set H_hrv = (flow * 0.34 * (1 - wrg)) / 1000 %}

      {# GESAMT-H (Hülle + Wind + HRV) #}
      {# Zielwert bei 14km/h: ca. 0.084 kW/K #}
      {{ (H_basis + H_wind_zuschlag + H_hrv) | round(5) }}
    availability: >
      {{ states('input_number.h_kw_per_k')|is_number 
         and states('sensor.wind_speed_ms')|is_number }}