sensor:
- name: "Heating Preheat Offset Dynamic Uncapped"
  unit_of_measurement: "K"
  state: >
    {% set h_wind = states('sensor.H_kW_per_K_effective') | float(0.08) %}
    {% set c_real = states('input_number.building_heat_capacity') | float(7.5) %}
    {% set delta_t = states('sensor.deltaT') | float(20) %}
    {% set hours_to_bridge = 22 - 6 %}
    {% set total_energy_loss = h_wind * delta_t * hours_to_bridge %}
    {% set solar_gains = states('sensor.solar_gains_average') | float(0) %}
    {% set internal_gains = states('sensor.internal_gains_average') | float(0) %}
    {% set total_gains = ((solar_gains + internal_gains) * hours_to_bridge) / 1000 %}
    {% set needed_offset = (total_energy_loss - total_gains) / c_real) %}
    {{ needed_offset | round(2) }}
- name: "Heating Preheat Offset Dynamic"
  unit_of_measurement: "K"
  state: >
    {% set uncapped = states('sensor.heating_preheat_offset_dynamic_uncapped') | float(0) %}
    {% set max_offset = states('input_number.heating_max_offset_k') | float(2.5) %}
    {% if uncapped > max_offset %}
      {{ max_offset }}
    {% else %}
      {{ uncapped }}
    {% endif %}