trigger:
  - platform: time_pattern
    seconds: "/30"
sensor:
  - name: "Heating Energy Debt Tracker"
    unique_id: heating_energy_debt_tracker
    unit_of_measurement: 'Wh'
    device_class: energy
    state: >
      {# 1. Die physikalische Nettobilanz in Watt (Sonne + Heizung - Verluste) #}
      {# WICHTIG: Die Formel im sensor.heating_net_balance muss wie unten beschrieben korrigiert sein! #}
      {% set net_power = states('sensor.heating_net_balance') | float(0) %}
      
      {# 2. Zeitintervall: 30 Sekunden in Stunden umrechnen #}
      {% set interval_hours = 30 / 3600 %}
      
      {# 3. Energieänderung in dieser Periode (Wh) #}
      {% set delta_energy = net_power * interval_hours %}
      
      {# 4. Alten Kontostand holen und neuen berechnen #}
      {% set previous_debt = states('sensor.heating_energy_debt_tracker') | float(0) %}
      
      {{ (previous_debt + delta_energy) | round(2) }}
    attributes:
      current_net_w: "{{ states('sensor.heating_net_balance') }}"
      status: >
        {% set net = states('sensor.heating_net_balance') | float(0) %}
        {% if net > 50 %}
          Konto wird geladen (Heizung/Sonne > Verlust)
        {% elif net < -50 %}
          Konto sinkt (Verlust > Gewinne)
        {% else %}
          Energetisches Gleichgewicht
        {% endif %}