sensor:
- name: "Heating Power bad"
  unique_id: heating_power_bad
  unit_of_measurement: "W"
  device_class: power
  state_class: measurement
  state: >
    {% set climate_state = states('climate.climate_room_bad') %}
    {% if climate_state == 'off' %}
      0
    {% else %}
      {% set voltage = states('sensor.pv_m1_ac_voltage_an') | float(230) %}

      {% set current = states('input_number.heater_bad_rated_a') | float(0) %}
      {{ current * voltage | round(0) }}
    {% endif %}
    