sensor:
- name: deltaT_24h
  unit_of_measurement: "K"
  state: >
    {% set ti = states('sensor.inside_temp_mean_24h')|float(none) %}
    {% set to = states('sensor.outside_temp_mean_24h')|float(none) %}
    {% if ti is not none and to is not none %}
      {{ max(ti - to, 0) | round(2) }}
    {% else %} unknown {% endif %}
  availability: >
    {{ states('sensor.inside_temp_mean_24h') not in ['unknown','unavailable','none']
       and states('sensor.outside_temp_mean_24h') not in ['unknown','unavailable','none'] }}
- name: kWh_per_K_day_rolling
  unit_of_measurement: "kWh/(K·Tag)"
  state: >
    {% set e = states('sensor.heating_usage_daily_total')|float(0) %}
    {% set dT = states('sensor.deltaT_24h')|float(0) %}
    {{ (e / dT) if dT > 0 else 0 | round(3) }}
- name: Wh_per_K_day_rolling
  unit_of_measurement: "Wh/(K·Tag)"
  state: >
    {{ (states('sensor.kWh_per_K_day_rolling')|float(0) * 1000) | round(0) }}
- name: H_kW_per_K_rolling
  unit_of_measurement: "kW/K"
  state: >
    {{ (states('sensor.kWh_per_K_day_rolling')|float(0) / 24.0) | round(3) }}