binary_sensor:
- name: "Heizung Preis günstig"
  unique_id: heating_price_is_cheap_now
  state: >-
    {% set ignore = is_state('input_boolean.heating_ignore_price','on') %}
    {% set thr = states('input_number.tibber_threshold_today')|float(0) %}
    {% set p   = states('sensor.backerstrasse_3b_strompreis')|float(99) %}
    {{ ignore or (p > 0 and thr > 0 and p <= thr) }}
  attributes:
    current_price_eur: "{{ states('sensor.backerstrasse_3b_strompreis') }}"
    threshold_eur:     "{{ states('input_number.tibber_threshold_today') }}"
    pmax_eur:          "{{ states('input_number.tibber_pmax_today') }}"
    cutoff_pct:        "{{ states('input_number.price_percentile_cutoff') }}"
- name: "Heizung erlaubt jetzt"
  unique_id: heating_allowed_now
  state: >-
    {% set preheat = now().hour >= 0 and now().hour < 6 %}
    {% set block   = is_state('input_boolean.heating_block_daytime','on') %}
    {% set priceok = is_state('binary_sensor.heizung_preis_gunstig','on') %}
    {% set pvex    = (states('sensor.filtered_exported_power_w')|float(0)) >
                     (states('input_number.pv_excess_threshold_w')|float(0)) %}
    {% set midday  = now().hour >= 12 and now().hour < 14 %}
    {% set topupok = pvex and midday %}
    {{ preheat or ( (not block) and (priceok or topupok) ) }}
  attributes:
    preheat_window:        "{{ now().hour >= 0 and now().hour < 6 }}"
    midday_topup_window:   "{{ now().hour >= 12 and now().hour < 14 }}"
    pv_excess: >-
      {{ (states('sensor.filtered_exported_power_w')|float(0)) >
         (states('input_number.pv_excess_threshold_w')|float(0)) }}
    price_ok:              "{{ is_state('binary_sensor.heizung_preis_gunstig','on') }}"
    blocking_enabled:      "{{ is_state('input_boolean.heating_block_daytime','on') }}"
