sensor:
- name: "Heat Battery Total Discharge"
  unit_of_measurement: "W"
  device_class: power
  state_class: measurement
  state: >
    {% set room_sensors = [
      'sensor.heat_battery_discharge_power_bad',
      'sensor.heat_battery_discharge_power_buero_fabian',
      'sensor.heat_battery_discharge_power_buero_merja',
      'sensor.heat_battery_discharge_power_flur',
      'sensor.heat_battery_discharge_power_kueche',
      'sensor.heat_battery_discharge_power_schlafzimmer',
      'sensor.heat_battery_discharge_power_speisekammer',
      'sensor.heat_battery_discharge_power_wohnzimmer'
    ] %}
    {% set temp = room_sensors | map('states') | map('float', 0) | sum %}
    {{ temp | round(2) }}