sensor:
- name: "Heating Net Balance"
  unique_id: heating_net_balance
  unit_of_measurement: 'W'
  device_class: power
  state_class: measurement
  state: >
    {# GEWINNE (Positiv) #}
    {% set internal = states('sensor.internal_gains_total') | float(0) %}
    {% set solar = states('sensor.solar_gains') | float(0) %}
    {% set heating = states('sensor.heating_power') | float(0) %}
    
    {# VERLUSTE (Negativ) #}
    {% set h_eff = states('sensor.h_kw_per_k_effective') | float(0) * 1000 %}
    {% set delta_t = states('sensor.deltaT') | float(0) %}
    {% set losses = h_eff * delta_t %}

    {# Bilanz: Alles was reinwärmt MINUS was rausgeht #}
    {{ (internal + solar + heating - losses) | round(0) }}

- name: "Delta K Compensation Power"
  unique_id: delta_k_compensation_power
  unit_of_measurement: 'W'
  device_class: power
  state_class: measurement
  state: >
    {# Zeigt an, wie viel Watt die Heizung leisten MUSS, damit die Bilanz >= 0 wird #}
    {% set h_eff = states('sensor.h_kw_per_k_effective') | float(0) * 1000 %}
    {% set losses = h_eff * (states('sensor.deltaT') | float(0)) %}
    {% set passive_gains = (states('sensor.internal_gains_total') | float(0)) + (states('sensor.solar_gains') | float(0)) + (states('sensor.heat_battery_total_discharge') | float(0)) %}
    
    {{ (losses - passive_gains) | round(0) }}