sensor:
- name: heat_loss_00_06_kwh
  unit_of_measurement: "kWh"
  state: >
    {% set To = states('sensor.outside_temp_mean_00_06_sql')|float(none) %}
    {% set Ti = states('sensor.inside_temp_mean_00_06_sql')|float(none) %}
    {% set H  = states('sensor.H_kW_per_K_effective')|float(0.072) %}
    {% if To is not none and Ti is not none and H>0 %}
      {{ (H * max(Ti-To,0) * 6) | round(2) }}
    {% elif To is not none and H>0 %}
      {{ (H * max(22-To,0) * 6) | round(2) }}   {# Fallback, falls Innenmittel fehlt #}
    {% else %} {{ iif(false,0,0) }} {% endif %}