sensor:
- name: "heating_usage_total"
  unit_of_measurement: "kWh"
  device_class: energy
  state_class: total_increasing
  # Summe aller Zonen/Matten-Energiesensoren:
  state: >-
    {% set invalid = ['unknown','unavailable','none','', None] %}
    {% set src = [
      'sensor.heating_usage_wohnzimmer',
      'sensor.heating_usage_kueche',
      'sensor.heating_usage_flur',
      'sensor.heating_usage_schlafzimmer',
      'sensor.heating_usage_buero_merja',
      'sensor.heating_usage_buero_fabian',
      'sensor.heating_usage_speisekammer',
      'sensor.heating_usage_bad'
    ] %}

    {# previous value (used whenever any input is missing) #}
    {% set prev_raw = this.state %}
    {% set prev = (prev_raw | float(none)) if prev_raw not in invalid else none %}

    {# require ALL sensors valid #}
    {% set ns = namespace(all_ok=true) %}
    {% for e in src %}
      {% if states(e) in invalid %}
        {% set ns.all_ok = false %}
      {% endif %}
    {% endfor %}

    {% if ns.all_ok %}
      {% set ns = namespace(total_wh=0.0) %}
      {% for e in src %}
        {% set ns.total_wh = ns.total_wh + (states(e) | float(0)) %}
      {% endfor %}
      {% set computed_kwh = ns.total_wh / 1000 %}

      {# enforce total_increasing: never go below previous #}
      {% if prev is not none %}
        {{ [prev, computed_kwh] | max }}
      {% else %}
        {{ computed_kwh }}
      {% endif %}
    {% else %}
      {# if anything missing -> always report previous; if none yet -> unknown #}
      {{ prev if prev is not none else 'unknown' }}
    {% endif %}
  attributes:
    missing_sources: >-
      {% set invalid = ['unknown','unavailable','none','', None] %}
      {% set src = [
        'sensor.heating_usage_wohnzimmer',
        'sensor.heating_usage_kueche',
        'sensor.heating_usage_flur',
        'sensor.heating_usage_schlafzimmer',
        'sensor.heating_usage_buero_merja',
        'sensor.heating_usage_buero_fabian',
        'sensor.heating_usage_speisekammer',
        'sensor.heating_usage_bad'
      ] %}
      {{ src | select('in', src) | list
         | reject('equalto', none) | list
         | select('string') | list
         | selectattr('', 'defined') | list }}