sensor:
- name: "Heizenergie spezifisch letztes Jahr"
  unique_id: heizenergie_spezifisch_letztes_jahr
  unit_of_measurement: "kWh/m²·a"
  state_class: measurement
  device_class: energy
  state: >
    {% set e = states('sensor.heizenergie_letztes_jahr') | float(0) %}
    {% if e <= 0 %}
      0
    {% else %}
      {{ (e / 141) | round(5) }}
    {% endif %}