sensor:
  - name: inside_temp_mean_now
    unique_id: inside_temp_mean_now
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    state: >
      {# Liste deiner Temperatur-Sensoren #}
      {% set sensors = [
        'sensor.temperature_wohnzimmer',
        'sensor.temperature_kueche',
        'sensor.temperature_flur_1',
        'sensor.temperature_flur_2',
        'sensor.temperature_flur_3',
        'sensor.temperature_schlafzimmer',
        'sensor.temperature_buero_fabian',
        'sensor.temperature_buero_merja',
        'sensor.temperature_bad',
        'sensor.temperature_speisekammer'
      ] %}
      {% set ns = namespace(vals=[]) %}
      {% for e in sensors %}
        {% set v = states(e) %}
        {% set ns.vals = ns.vals + [v|float] %}
      {% endfor %}
      {% if ns.vals|length > 0 %}
        {{ (ns.vals|sum / (ns.vals|length))|round(2) }}
      {% else %} unknown {% endif %}
