sensor:
- name: inside_temp_mean_now
  unique_id: inside_temp_mean_now
  unit_of_measurement: "°C"
  state: >
    {# Liste deiner Temperatur-Sensoren #}
    {% set sensors = [
      'sensor.temperature_wohnzimmer',
      'sensor.temperature_kueche',
      'sensor.temperature_flur_1',
      'sensor.temperature_flur_2',
      'sensor.temperature_flur_3',
      'sensor.temperature_schlafzimmer',
      'sensor.temperature_buero_fabian',
      'sensor.temperature_buero_merja',
      'sensor.temperature_bad'
    ] %}
    {% set vals = [] %}
    {% for e in sensors %}
      {% set v = states(e) %}
      {% if v is number %}
        {% set vals = vals + [ v|float ] %}
      {% endif %}
    {% endfor %}
    {% if vals|length > 0 %}
      {{ (vals|sum / (vals|length))|round(2) }}
    {% else %} unknown {% endif %}
  attributes:
    sensors_used: >
      {% set sensors = [
        'sensor.temperature_wohnzimmer',
        'sensor.temperature_kueche',
        'sensor.temperature_flur_1',
        'sensor.temperature_flur_2',
        'sensor.temperature_flur_3',
        'sensor.temperature_schlafzimmer',
        'sensor.temperature_buero_fabian',
        'sensor.temperature_buero_merja',
        'sensor.temperature_bad'
      ] %}
      {% set used = [] %}
      {% for e in sensors %}
        {% if states(e) is number %}
          {% set used = used + [e] %}
        {% endif %}
      {% endfor %}
      {{ used|join(', ') }}
    count: >
      {% set sensors = [
        'sensor.temperature_wohnzimmer',
        'sensor.temperature_kueche',
        'sensor.temperature_flur_1',
        'sensor.temperature_flur_2',
        'sensor.temperature_flur_3',
        'sensor.temperature_schlafzimmer',
        'sensor.temperature_buero_fabian',
        'sensor.temperature_buero_merja',
        'sensor.temperature_bad'
      ] %}
      {% set c = 0 %}
      {% for e in sensors %}
        {% if states(e) is number %}
          {% set c = c + 1 %}
        {% endif %}
      {% endfor %}
      {{ c }}