sensor:
- name: "Internal Gains Misc"
  unique_id: internal_gains_misc
  unit_of_measurement: 'W'
  device_class: power
  state: >
    {% set total_load = states('sensor.solar_house_consumption_w') | float(0) %}
    
    {# Hier ziehen wir die Roh-Leistungswerte (W) der Geräte ab #}
    {% set dryer_w = states('sensor.trockner_power') | float(0) %}
    {% set washer_w = states('sensor.waschmaschine_power') | float(0) %}
    {% set dish_w = states('sensor.kuche_geschirrspuler_power') | float(0) %}
    {% set bwwp_w = states('sensor.heating_pump_power') | float(0) %}
    {% set ir_heating_w = states('sensor.heating_power') | float(0) %}
    {% set hrv_w = states('sensor.shellyplus2pm_485519a264d8_switch_1_power') | float(0) %}
    {% set pv_w = states('sensor.solar_grid_to_battery_w') | float(0) %}
    
    {# Alles was übrig bleibt, wird zu 100% als Wärme gewertet #}
    {% set diffuse = total_load - dryer_w - washer_w - dish_w - bwwp_w - ir_heating_w - hrv_w - pv_w %}
    
    {{ [0, diffuse] | max | round(1) }}