sensor:
- name: "Internal Gains PV"
  unique_id: internal_gains_pv
  unit_of_measurement: 'W'
  device_class: power
  state: >
    {% set invalid = ['unknown','unavailable','none','', None] %}
    {% set ac_pwr = states('sensor.pv_ac_power') | float(0) %}
    {% set bat_pwr = states('sensor.pv_battery1_power') | float(0) %}
    
    {# 1. Die gesamte Leistung, die der Wechselrichter gerade verarbeitet (Durchsatz) #}
    {# Wir nehmen den AC-Wert als Basis für den Durchsatz #}
    {% set throughput = ac_pwr %}

    {# 2. Wechselrichter-Verlust (Pauschal 2,5% vom Durchsatz + 15W Eigenverbrauch) #}
    {# Das entspricht dem Wirkungsgrad von ca. 97,5% des SE10K #}
    {% if throughput > 10 %}
      {% set wr_loss = (throughput * 0.025) + 15 %}
    {% else %}
      {% set wr_loss = 8 %}
    {% endif %}

    {# 3. Batterie-Verlust (Wärme im BYD Turm bei chemischer Entladung/Ladung) #}
    {# Hier rechnen wir mit 2% Verlustleistung im Batterieturm #}
    {% set bat_loss = (bat_pwr | abs) * 0.02 %}

    {# Gesamtsumme der internen Gewinne #}
    {{ (wr_loss + bat_loss) | round(2) }}