sensor:
- name: "Internal Gains Trockner"
  unique_id: internal_gains_trockner
  unit_of_measurement: 'W'
  device_class: power
  state: >
    {# Wir nehmen den kW-Wert der Ableitung und wandeln ihn in Watt #}
    {# Falls die Ableitung in kW kommt, hier mit 1000 multiplizieren #}
    {% set p = states('sensor.trockner_power') | float(0) %}
    
    {# Da der kWh-Zähler oft nur in groben Schritten springt, #}
    {# nutzen wir eine einfache Plausibilität: #}
    {% if p > 10 %}
       {{ (p * 0.9) | round(1) }}
    {% else %}
      0.0
    {% endif %}