sensor:
- name: "Internal Gains Total"
  unique_id: internal_gains_total
  unit_of_measurement: 'W'
  device_class: power
  state: >
    {# A: Technik-Gewinne mit Wirkungsgraden #}
    {% set tech = states('sensor.internal_gains_trockner') | float(0) + 
                        states('sensor.internal_gains_waschmaschine') | float(0) +
                        states('sensor.internal_gains_dishwasher') | float(0) +
                        states('sensor.internal_gains_heating_pump') | float(0) %}
          
    {# B: 100% Gewinne (Misc) #}
    {% set full_gains = states('sensor.internal_gains_misc') | float(0) %}
    
    {# C: System-Gewinne (PV-Wechselrichter & HRV Lüftung) #}
    {% set system = states('sensor.internal_gains_pv') | float(0) + 
                    states('sensor.internal_gains_hrv') | float(0) %}
    
    {# D: Personen-Gewinne #}
    {% set persons = states('sensor.internal_gains_persons') | float(0) %}
    
    {{ (tech + full_gains + system + persons) | round(0) }}