sensor:
- name: "Internal Gains Car Charger"
  unique_id: internal_gains_car_charger
  unit_of_measurement: 'W'
  device_class: power
  state: >
    {% set p = states('sensor.goe_288025_nrg_11') | float(0) %}
    {% if p > 5 %}
      {% set R_per_phase = 0.0175 * 4 / 4 %}
      
      {% set i_l1 = (states('sensor.goe_288025_nrg_7') | float(0)) / (states('sensor.pv_ac_voltage_an') | float(230)) %}
      {% set i_l2 = (states('sensor.goe_288025_nrg_8') | float(0)) / (states('sensor.pv_ac_voltage_bn') | float(230)) %}
      {% set i_l3 = (states('sensor.goe_288025_nrg_9') | float(0)) / (states('sensor.pv_ac_voltage_cn') | float(230)) %}

      {# Jede Phase einzeln: P = I^2 * R #}
      {% set P_loss_house = (i_l1**2 * R_per_phase) + (i_l2**2 * R_per_phase) + (i_l3**2 * R_per_phase) %}
      {{ P_loss_house | round(1) }}
    {% else %}
      0.0
    {% endif %}
  attributes: 
    consumes: >
      {% set p = states('sensor.goe_288025_nrg_11') | float(0) %}
      {% if p > 5 %}
        {# Hier die vollen 15m für den Misc-Abzug #}
        {% set R_per_phase = 0.0175 * 15 / 4 %}
        
        {% set i_l1 = (states('sensor.goe_288025_nrg_7') | float(0)) / (states('sensor.pv_ac_voltage_an') | float(230)) %}
        {% set i_l2 = (states('sensor.goe_288025_nrg_8') | float(0)) / (states('sensor.pv_ac_voltage_bn') | float(230)) %}
        {% set i_l3 = (states('sensor.goe_288025_nrg_9') | float(0)) / (states('sensor.pv_ac_voltage_cn') | float(230)) %}

        {% set P_loss_total = (i_l1**2 * R_per_phase) + (i_l2**2 * R_per_phase) + (i_l3**2 * R_per_phase) %}
        {{ P_loss_total | round(1) }}
      {% else %}
        0.0
      {% endif %}