sensor:
- name: "Internal Gains PV"
  unique_id: internal_gains_pv
  unit_of_measurement: 'W'
  device_class: power
  state: >
    {# Rohwerte laden #}
    {% set pv_dc = states('sensor.pv_dc_power') | float(0) %}
    {% set ac_pwr = states('sensor.pv_ac_power') | float(0) %}
    {% set bat_pwr = states('sensor.pv_battery1_power') | float(0) %}
    
    {# Definition SolarEdge: bat_pwr > 0 ist LADEN, bat_pwr < 0 ist ENTLADEN #}
    
    {# 1. Was geht in den Wechselrichter REIN? #}
    {# PV Leistung + Batterie-Entladung (wenn negativ) #}
    {% set energy_in = pv_dc + (bat_pwr | abs if bat_pwr < 0 else 0) %}
    
    {# 2. Was kommt aus dem Wechselrichter RAUS? #}
    {# AC Leistung ins Haus + Batterie-Ladung (wenn positiv) #}
    {% set energy_out = ac_pwr + (bat_pwr if bat_pwr > 0 else 0) %}
    
    {# 3. Die Differenz ist die Abw채rme des WR #}
    {% set wr_loss = energy_in - energy_out %}

    {# 4. Batterie-Eigenverlust (Zellen/BMS im BYD Turm) #}
    {# Wir nehmen ca. 3% Verlust der Batterie-Leistung als W채rme im Turm an #}
    {% set bat_loss = (bat_pwr | abs) * 0.03 %}

    {# Plausibilit채ts-Check #}
    {% if energy_in > 50 %}
      {# Wenn die Anlage l채uft, nehmen wir WR-Verlust + Batterie-Verlust #}
      {# Wir limitieren den WR-Verlust auf max 10%, um Messfehler abzufangen #}
      {% set final_loss = [wr_loss, (energy_in * 0.10)] | min %}
      {{ ([10, (final_loss + bat_loss)] | max) | round(2) }}
    {% else %}
      {# Standby nachts #}
      {{ 5.0 }}
    {% endif %}