sensor:
- name: "Internal Gains Misc"
  unique_id: internal_gains_misc
  unit_of_measurement: 'W'
  device_class: power
  state: >
    {% set total_load = states('sensor.solar_house_consumption_w') | float(0) %}
    
    {# Energie die konsumiert wurde von internen gewinnen #}
    {% set gain_consumes = states.sensor 
              | selectattr('entity_id', 'search', '^sensor.internal_gains_') | expand 
              | selectattr('attributes.consumes', 'defined') | map(attribute='attributes.consumes') 
              | map('float') | list | sum %}
    
    {# Heizung betrachten wir separat #}
    {% set ir_heating_w = states('sensor.heating_power') | float(0) %}

    {# Sachen sie ausserhalb des Hauses ihre Wärme verlieren #}
    {% set outside_kitchen_w = states('sensor.kuche_aussen_power') | float(0) %}

    {# Alles was übrig bleibt, wird zu 100% als Wärme gewertet #}
    {% set diffuse = total_load - gain_consumes - ir_heating_w - outside_kitchen_w %}
    
    {{ [0, diffuse] | max | round(1) }}
  attributes:
    bill: >
      {% set total = states('sensor.solar_house_consumption_w') | float(0) %}
      {% set gains = states.sensor 
              | selectattr('entity_id', 'search', '^sensor.internal_gains_') 
              | selectattr('attributes.consumes', 'defined') 
              | list %}
        
      Total House: {{ total }} W
      ---
      {% for gain in gains %}
      {{ gain.name }}: -{{ gain.attributes.consumes }} W
      {% endfor %}
      IR-Heating: -{{ states('sensor.heating_power') | float(0) }} W
      Küche-Außen: -{{ states('sensor.kuche_aussen_power') | float(0) }} W
      ---
      Result Misc: {{ [0, total - (gains | map(attribute='attributes.consumes') | map('float') | sum) - (states('sensor.heating_power')|float) - (states('sensor.kuche_aussen_power')|float)] | max | round(1) }} W
