sensor:
- name: heater_bad_max_current_a
  unit_of_measurement: "A"
  state: "{{ (states('sensor.heater_bad_max_current_ma')|float(0))/1000 }}"
- name: heater_kueche_max_current_a
  unit_of_measurement: "A"
  state: "{{ (states('sensor.heater_kueche_max_current_ma')|float(0))/1000 }}"
- name: heater_schlafzimmer_max_current_a
  unit_of_measurement: "A"
  state: "{{ (states('sensor.heater_schlafzimmer_max_current_ma')|float(0))/1000 }}"
- name: heater_flur_max_current_a
  unit_of_measurement: "A"
  state: "{{ (states('sensor.heater_flur_max_current_ma')|float(0))/1000 }}"
- name: heater_speisekammer_max_current_a
  unit_of_measurement: "A"
  state: "{{ (states('sensor.heater_speisekammer_max_current_ma')|float(0))/1000 }}"
- name: heater_wohnzimmer_max_current_a
  unit_of_measurement: "A"
  state: "{{ (states('sensor.heater_wohnzimmer_max_current_ma')|float(0))/1000 }}"
- name: heater_buero_merja_max_current_a
  unit_of_measurement: "A"
  state: "{{ (states('sensor.heater_buero_merja_max_current_ma')|float(0))/1000 }}"
- name: heater_buero_fabian_max_current_a
  unit_of_measurement: "A"
  state: "{{ (states('sensor.heater_buero_fabian_max_current_ma')|float(0))/1000 }}"