sensor:
# Mittelwert der nächsten 24h Außentemperatur aus dem daily-JSON
- name: outside_temp_forecast_24h_c
  unit_of_measurement: "°C"
  state: >-
    {% set raw = states('input_text.weather_home_daily_json') %}
    {% set arr = raw | from_json(default=[]) %}
    {% set now_ts = as_timestamp(now()) %}
    {% set ahead = now_ts + 24*3600 %}
    {% set vals = [] %}
    {% for e in arr %}
      {% set dt = as_timestamp(e.datetime if e.datetime is defined else e['datetime']) %}
      {% if dt is number and now_ts <= dt <= ahead %}
        {% set th = e.temperature if e.temperature is defined else e['temperature'] %}
        {% set tl = e.templow    if e.templow    is defined else e.get('templow') %}
        {% if (th is number) and (tl is number) %}
          {% set vals = vals + [ (th|float + tl|float)/2 ] %}
        {% elif th is number %}
          {% set vals = vals + [ th|float ] %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {% if vals|length > 0 %}
      {{ (vals | sum / (vals|length)) | round(2) }}
    {% else %}
      {{ states('sensor.outside_temp_mean_24h_sql')|float(8) }}
    {% endif %}
# Mittelwert der aktuellen Soll-Temperaturen aller Zonen
- name: inside_target_mean_c
  unit_of_measurement: "°C"
  state: >-
    {% set climates = [
      'climate.raum_bad','climate.raum_kueche','climate.raum_schlafzimmer',
      'climate.raum_flur','climate.raum_speisekammer','climate.raum_wohnzimmer',
      'climate.raum_buero_merja','climate.raum_buero_fabian'
    ] %}
    {% set vals = [] %}
    {% for ce in climates %}
      {% set t = state_attr(ce,'temperature') %}
      {% if t is number %}{% set vals = vals + [ t|float ] %}{% endif %}
    {% endfor %}
    {{ ((vals|sum / (vals|length)) if (vals|length>0) else 22) | round(2) }}
# ΔT-Forecast für Preheat: Innen-Zielmittel minus Außen-Forecast
- name: delta_t_forecast_k
  unit_of_measurement: "K"
  state: >-
    {{ (states('sensor.inside_target_mean_c')|float(22)
      - states('sensor.outside_temp_forecast_24h_c')|float(8)) | round(3) }}