sensor:
  - name: "Power Price NT"
    unique_id: power_price_nt
    unit_of_measurement: "€/kWh"
    device_class: monetary
    state: >
      {% if states('input_select.power_provider') == 'Octopus Go' %}
        {{ states('sensor.power_price_nt_octopus_go') | float(0) }}
      {% elif states('input_select.power_provider') == 'Tibber' %}
        {{ states('sensor.power_price_nt_tibber') | float(0) }}
      {% endif %}