trigger:
  - platform: time_pattern
    minutes: "/15" # Based on day ahead market timer
sensor:
  - name: "Power Price Octopus Go"
    unique_id: power_price_octopus_go
    unit_of_measurement: "€/kWh"
    device_class: monetary
    state: >
      {{ states('sensor.octopus_a_ee9b6cf5_electricity_price') | float(0) }}