sensor:
- name: "Power Price"
  unique_id: power_price
  unit_of_measurement: "€/kWh"
  device_class: monetary
  state: >
    {% if states('input_select.power_provider') == 'Octopus Go' %}
      {{ states('sensor.power_price_octopus_go') | float(0) }}
    {% elif states('input_select.power_provider') == 'Tibber' %}
      {{ states('sensor.power_price_tibber') | float(0) }}
    {% endif %}