sensor:
  - name: "Power Price HT Tibber"
    unique_id: power_price_ht_tibber
    unit_of_measurement: "€/kWh"
    device_class: monetary
    state: >
      {{ states('input_number.tibber_price_dw_06_24') | float(0) }}