binary_sensor:
- name: "Preheat erlaubt (Demand-Weighted)"
  state: >-
    {% set p = states('sensor.preheat_spread_ratio_bedarfgewichtet') | float(0) %}
    {% set pD = states('sensor.preheat_penalty_faktor')|float(0) %}
    {% set m  = states('input_number.preheat_margin_pct')|float(0.02) %}
    {% if p>0 and pD>0 %}
      {{ p - pD > m }}
    {% else %}
      false
    {% endif %}