sensor:
- name: "Preheat Penalty Faktor"
  unit_of_measurement: "x"
  state: >-
    {% set H = states('sensor.h_kw_per_k_effective') | float(0) %}
    {% set C = states('input_number.building_heat_capacity') | float(0) %}
    {% set dt = states('input_number.preheat_dt_hours') | float(12) %}

    {% if H > 0 and C > 0 and dt > 0 %}
      {{ (2.718281828 ** ((H / C) * dt)) | round(3) }}
    {% else %}
      {# restart-safe: keep previous value if it exists, else 0 #}
      {% set prev = this.state %}
      {% if prev not in ['unknown', 'unavailable', 'none', None, ''] %}
        {{ prev }}
      {% else %}
        0
      {% endif %}
    {% endif %}
- name: "Preheat Spread Ratio (bedarfgewichtet)"
  unit_of_measurement: "x"
  state: >-
    {% set pN = states('sensor.power_price_nt')|float(0) %}
    {% set pD = states('sensor.power_price_ht')|float(0) %}
    {% if pN>0 and pD>0 %}
      {{ (pD/pN) | round(3) }}
    {% else %}
      {# restart-safe: keep previous value if it exists, else 0 #}
      {% set prev = this.state %}
      {% if prev not in ['unknown', 'unavailable', 'none', None, ''] %}
        {{ prev }}
      {% else %}
        0
      {% endif %}
    {% endif %}