sensor:
  # --- SUMMEN-SENSOR (Korrigiert) ---
  - name: "Solar Gains"
    unique_id: solar_gains
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    state: >
      0