sensor: 
- name: Solaredge Battery Input Power
  unit_of_measurement: "kW"
  device_class: "power"
  state: >
    {% set energy = states('sensor.solaredge_gespeicherte_energie') | float %}
    {% if energy < 0 %}
    {{ energy * -1 }}
    {% else %}
    0
    {% endif %}