sensor:
- name: "Solar Gains"
  unique_id: solar_gains
  unit_of_measurement: 'W'
  device_class: power
  state: >
    {% set radiation = states('sensor.barsinghausen_hohenb_sonneneinstrahlung') | float(0) %}
    {% set azimuth = state_attr('sun.sun', 'azimuth') | float(0) %}
    {% set elevation = state_attr('sun.sun', 'elevation') | float(0) %}
    {% set g = 0.53 %}

    {% if elevation <= 0 or radiation <= 0 %}
      0
    {% else %}
      {# Helfer-Makro: Rechnet Position (0-100) in Faktor (0.0-1.0) um #}
      {% macro pos(entity) %}
        {{ (state_attr(entity, 'current_position') | float(100) / 100.0) }}
      {% endmacro %}

      {# --- SÜD-FASSADE --- #}
      {% set shade_south = 1.0 if elevation < 35 else (0.1 if elevation > 65 else 0.4) %}
      
      {# Multiplikation der Fensterfläche mit dem Öffnungsgrad #}
      {% set f_fabian = 1.60 * (pos('cover.rollade_buero_fabian') | float) %}
      {% set f_wz_l = 2.715 * (pos('cover.rollade_wohnzimmer_links') | float) %}
      {% set f_wz_r = 2.715 * (pos('cover.rollade_wohnzimmer_rechts') | float) %}
      {% set f_kueche_s = 3.22 * (pos('cover.rollade_kueche_links') | float) %}
      
      {% set total_south = f_fabian + ((f_wz_l + f_wz_r) * shade_south) + f_kueche_s %}
      {% set gain_south = (total_south * g * radiation) if (azimuth > 100 and azimuth < 260) else 0 %}

      {# --- OST-FASSADE (Jetzt Speisekammer nach deinem Tausch) --- #}
      {% set shade_east = 1.0 if elevation < 20 else 0.2 %}
      {% set f_speise = 0.24 * (pos('cover.rollade_speisekammer') | float) %}
      
      {% set total_east = f_speise * shade_east %}
      {% set gain_east = (total_east * g * radiation) if (azimuth > 10 and azimuth < 170) else 0 %}

      {# --- WEST-FASSADE (Jetzt Küche rechts / Merja) --- #}
      {% set f_kueche_o = 2.91 * (pos('cover.rollade_kueche_rechts') | float) %}
      {% set f_merja = 3.22 * (pos('cover.rollade_buero_merja') | float) %}
      
      {% set total_west = (f_kueche_o + f_merja) %}
      {% set gain_west = (total_west * g * radiation) if (azimuth > 190 and azimuth < 350) else 0 %}

      {# --- NORD-FASSADE --- #}
      {% set f_schlaf = 1.60 * (pos('cover.rollade_schlafzimmer') | float) %}
      {% set f_bad = 0.91 * (pos('cover.rollade_bad') | float) %}
      {% set f_hwr = 0.24 * (pos('cover.rollade_hwr') | float) %}
      {% set gain_north = (f_schlaf + f_bad + f_hwr) * g * radiation * 0.15 %}

      {{ (gain_south + gain_east + gain_west + gain_north) | round(0) }}
    {% endif %}