sensor:
- name: Solaredge Battery Output Power
  unit_of_measurement: "kW"
  device_class: "energy"
  state_class: total_increasing
  state: >
    {% set energy = states('sensor.solaredge_gespeicherte_energie') | float %}
    {% if energy > 0 %}
    {{ ( states('sensor.solaredge_battery_output_power') | float(0) ) + energy }}
    {% else %}
    {{ states('sensor.solaredge_battery_output_power') | float(0) }}
    {% endif %}