sensor:
- name: "Solar Gain Buero_fabian"
  unique_id: solar_gain_buero_fabian
  unit_of_measurement: 'W'
  device_class: power
  state_class: measurement
  state: >
    {% set rad = states('sensor.barsinghausen_hohenb_sonneneinstrahlung') | float(0) %}
    {% set ele = state_attr('sun.sun', 'elevation') | float(0) %}
    {% set azi = state_attr('sun.sun', 'azimuth') | float(0) %}
    {% set ns = namespace(total=0) %}


      
    {% if ele > 0 and ((azi - 180 + 180) % 360 - 180) | abs < 90 %}
      {% set pos = (state_attr('cover.rollade_buero_fabian', 'current_position') | float(100) / 100) %}
      
      {# Manuelle Umrechnung: Grad * 0.0174532925 #}
      {% set cos_factor = ((azi - 180) * 0.0174532925) | cos | abs %}
      
      {% set direct_factor = 1.0 %}
          {% if ele < 49.24 %}
            {% set direct_factor = 0.0 %}
          {% endif %}

      {% set sun_part = [pos, direct_factor]|min %}
      {% set shade_part = [0, pos - direct_factor]|max %}
      
      {% set sun_factor = sun_part + (shade_part * 0.15) %}
      {% set ns.total = ns.total + (0.848 * rad * cos_factor * sun_factor) %}
    {% endif %}

    {{ ns.total | round(0) }}