sensor: 
- name: Solaredge Battery Input Power
  unit_of_measurement: "kW"
  device_class: "power"
  state: >
    {% set energy = states('sensor.solaredge_gespeicherte_energie') | float %}
    {% if energy < 0 %}
    {{ ( states('sensor.solaredge_battery_input_power') | float(0) ) + energy * -1 }}
    {% else %}
    {{ states('sensor.solaredge_battery_input_power') | float(0) }}
    {% endif %}