sensor:
- name: "Solar Expected Gain Kueche"
  unique_id: solar_expected_gain_kueche
  unit_of_measurement: 'W'
  device_class: power
  state_class: measurement
  state: >
    {% set rad = states('sensor.barsinghausen_hohenb_sonneneinstrahlung') | float(0) %}
    {% set ele = state_attr('sun.sun', 'elevation') | float(0) %}
    {% set azi = state_attr('sun.sun', 'azimuth') | float(0) %}
    {% set ns = namespace(total=0) %}

    
      
    {% if ele > 0 and ((azi - 90 + 180) % 360 - 180) | abs < 90 %}
      {% set pos = 1.0 %}
      
      {# Manuelle Umrechnung von Grad in Bogenmaß: Grad * (Pi / 180) #}
      {% set cos_factor = ((azi - 90) * 0.0174532925) | cos | abs %}
      
      {% set direct_factor = 1.0 %}
          {# Hier nutzen wir ebenfalls die manuelle Umrechnung und den tan-Filter #}
          {% set shadow_h = 2.9 - (4.5 * ((ele * 0.0174532925) | tan)) %}
          {% set win_top = 1.94 %}
          {% set win_bottom = 0.0 %}
          {% set sun_h = [0, [shadow_h, win_top]|min - win_bottom]|max %}
          {% set direct_factor = [direct_factor, sun_h / 1.94] | min %}

      {% set sun_part = [pos, direct_factor]|min %}
      {% set shade_part = [0, pos - direct_factor]|max %}
      
      {% set sun_factor = sun_part + (shade_part * 0.15) %}
      {% set ns.total = ns.total + (1.5423 * rad * cos_factor * sun_factor) %}
    {% endif %}

    
      
    {% if ele > 0 and ((azi - 180 + 180) % 360 - 180) | abs < 90 %}
      {% set pos = 1.0 %}
      
      {# Manuelle Umrechnung von Grad in Bogenmaß: Grad * (Pi / 180) #}
      {% set cos_factor = ((azi - 180) * 0.0174532925) | cos | abs %}
      
      {% set direct_factor = 1.0 %}
          {% if ele < 49.97 %}
            {% set direct_factor = 0.0 %}
          {% endif %}

      {% set sun_part = [pos, direct_factor]|min %}
      {% set shade_part = [0, pos - direct_factor]|max %}
      
      {% set sun_factor = sun_part + (shade_part * 0.15) %}
      {% set ns.total = ns.total + (1.7059 * rad * cos_factor * sun_factor) %}
    {% endif %}

    {{ ns.total | round(0) }}