sensor:
- name: "Solar Gain Kueche"
  unique_id: solar_gain_kueche
  unit_of_measurement: 'W'
  device_class: power
  state_class: measurement
  state: >
    {% set rad = states('sensor.barsinghausen_hohenb_sonneneinstrahlung') | float(0) %}
    {% set ele = state_attr('sun.sun', 'elevation') | float(0) %}
    {% set azi = state_attr('sun.sun', 'azimuth') | float(0) %}
    {% set ns = namespace(total=0) %}


      
    {# --- Berechnung Fenster 1 --- #}
    {% if ele > 0 and ((azi - 90 + 180) % 360 - 180) | abs < 90 %}
      {% set pos = (state_attr('cover.rollade_kueche_links', 'current_position') | float(100) / 100) %}
      {% set cos_factor = ((azi - 90) | deg2rad | cos) | abs %}
      
      {% set direct_factor = 1.0 %}
          {% set shadow_h = 2.9 - (4.5 * (ele | deg2rad | tan)) %}
          {% set sun_h = [0, [shadow_h, 1.94]|min - 0.0]|max %}
          {% set direct_factor = [direct_factor, sun_h / 1.94] | min %}

      {% set sun_part = [pos, direct_factor]|min %}
      {% set shade_part = [0, pos - direct_factor]|max %}
      
      {% set sun_factor = sun_part + (shade_part * 0.15) %}
      {% set ns.total = ns.total + (1.5423000000000002 * rad * cos_factor * sun_factor) %}
    {% endif %}


      
    {# --- Berechnung Fenster 2 --- #}
    {% if ele > 0 and ((azi - 180 + 180) % 360 - 180) | abs < 90 %}
      {% set pos = (state_attr('cover.rollade_kueche_rechts', 'current_position') | float(100) / 100) %}
      {% set cos_factor = ((azi - 180) | deg2rad | cos) | abs %}
      
      {% set direct_factor = 1.0 %}
          {% if ele < 49.97 %}
            {% set direct_factor = 0.0 %}
          {% endif %}

      {% set sun_part = [pos, direct_factor]|min %}
      {% set shade_part = [0, pos - direct_factor]|max %}
      
      {% set sun_factor = sun_part + (shade_part * 0.15) %}
      {% set ns.total = ns.total + (1.705858 * rad * cos_factor * sun_factor) %}
    {% endif %}

    {{ ns.total | round(0) }}