binary_sensor:
  - name: "Vacation Mode"
    unique_id: vacation_mode
    state: >-
      {% set return_date = states('input_datetime.vacation_return') %}
      {% if return_date not in ['unknown', 'unavailable'] %}
        {{ now().date() < as_datetime(return_date).date() }}
      {% else %}
        false
      {% endif %}
  - name: "Vacation Mode Water Heater"
    unique_id: vacation_mode_water_heater
    state: >-
      {% set return_date = states('input_datetime.vacation_return') %}
      {% if return_date not in ['unknown', 'unavailable'] %}
        {{ now().date() < (as_datetime(return_date) - timedelta(days=1)).date() }}
      {% else %}
        false
      {% endif %}
