sensor:
- name: "Water Heating Pump Power"
  unique_id: water_heating_pump_power
  unit_of_measurement: "W"
  device_class: power
  state_class: measurement
  state: >
    {% set current = states('sensor.current_water_heating_pump') | float(0) / 1000 %}
    {% set voltage = states('sensor.pv_m1_ac_voltage_cn') | float(230) }
    {{ current * voltage | round(2) }}
    