sensor:
- name: wind_speed_kmh
  unit_of_measurement: "km/h"
  state: >
    {{ state_attr('weather.home','wind_speed')|float(0) }}
- name: wind_speed_ms
  unit_of_measurement: "m/s"
  state: >
    {{ state_attr('weather.home','wind_speed')|float(0) / 3.6 }}