sensor:
- name: wind_speed_now_kmh
  unit_of_measurement: "km/h"
  state_class: measurement
  state: >
    {{ state_attr('weather.home', 'wind_speed') | float(0) }}
  availability: >
    {{ state_attr('weather.home', 'wind_speed') is not none
       and states('weather.home') not in ['unknown','unavailable'] }}