id: '1763464703056'
alias: Override off when battery over 75%
description: ''
triggers:
- trigger: numeric_state
  entity_id:
  - sensor.pv_battery1_state_of_charge
  for:
    hours: 0
    minutes: 2
    seconds: 0
  above: 75
conditions: []
actions:
- action: input_boolean.turn_off
  metadata: {}
  data: {}
  target:
    entity_id: input_boolean.charge_solar_battery_override
mode: single