- alias: wohnzimmer Heizung Sicherheitsschalter
  id: heating_security_switch_wohnzimmer
  description: ""
  mode: single
  triggers:
    - trigger: numeric_state
      entity_id:
        - sensor.security_temperature_wohnzimmer_max
      above: 26
  conditions: []
  actions:
    - action: climate.set_hvac_mode
      metadata: {}
      target:
        entity_id: climate.climate_room_wohnzimmer
      data:
        hvac_mode: "off"