- alias: buero_merja Heizung Sicherheitsschalter
  id: heating_security_switch_buero_merja
  description: ""
  mode: single
  triggers:
    - trigger: numeric_state
      entity_id:
        - sensor.security_temperature_buero_merja_max
      above: 23.5
  conditions: []
  actions:
    - action: climate.set_hvac_mode
      metadata: {}
      target:
        entity_id: climate.climate_room_buero_merja
      data:
        hvac_mode: "off"