- alias: bad Heizung Sicherheitsschalter
  id: heating_security_switch_bad
  description: ""
  mode: single
  triggers:
    - trigger: numeric_state
      entity_id:
        - sensor.security_temperature_bad_max
      above: 23.5
  conditions: []
  actions:
    - action: climate.set_hvac_mode
      metadata: {}
      target:
        entity_id: climate.climate_room_bad
      data:
        hvac_mode: "off"