- alias: speisekammer Heizung Sicherheitsschalter
  id: heating_security_switch_speisekammer
  description: ""
  mode: single
  triggers:
    - trigger: numeric_state
      entity_id:
        - sensor.security_temperature_speisekammer_max
      above: 26
  conditions: []
  actions:
    - action: climate.set_hvac_mode
      metadata: {}
      target:
        entity_id: climate.climate_room_speisekammer
      data:
        hvac_mode: "off"