- alias: Licht an bad
  description: ""
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.presence_bad
      from: "off"
      to: "on"
  conditions:
    - condition: numeric_state
      entity_id: sensor.lux_bad
      below: 300
    - condition: time
      after: "09:00:00"
      before: "22:00:00"
  actions:
    - action: light.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: light.light_bad
  mode: single
- alias: Licht aus bad
  description: ""
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.presence_bad
      from: "on"
      to: "off"
  actions:
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: light.light_bad
  mode: single
