- alias: buero_fabian licht automatisch AN
  id: auto_light_buero_fabian_on
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_buero_fabian
      to: "on"
    - platform: numeric_state
      entity_id: sensor.lux_buero_fabian
      below: 120          # waterLowLux
      for: "00:00:05"
    - platform: state
      entity_id: input_boolean.auto_light_buero_fabian
      to: "on"

  condition:
    # Automatik muss an sein
    - condition: state
      entity_id: input_boolean.auto_light_buero_fabian
      state: "on"

    # Präsenz notwendig
    - condition: state
      entity_id: binary_sensor.presence_buero_fabian
      state: "on"

    # Lux muss UNTER 120 sein
    - condition: numeric_state
      entity_id: sensor.lux_buero_fabian
      below: 120

    # Licht nur einschalten, wenn es wirklich aus ist
    - condition: state
      entity_id: light.buero_fabian_lights
      state: "off"

    # Optional: wenn ForceOn vorhanden, diese Automation deaktivieren
    # indem ForceOn "off" sein muss
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ not states('input_boolean.force_on_buero_fabian') }}"
        - condition: state
          entity_id: input_boolean.force_on_buero_fabian
          state: "off"

  action:
    - variables:
        saved_brightness: "{{ states('input_number.buero_fabian_brightness') | int(0) }}"
        brightness: >
          {{ 300 if saved_brightness == 0 else saved_brightness }}
        color_temp: "{{ states('input_number.buero_fabian_color_temp') | int(370) }}"
    - service: light.turn_on
      target:
        entity_id: light.buero_fabian_lights
      data:
        brightness: "{{ brightness }}"
        color_temp: "{{ color_temp }}"
