- alias: Rollade rauf bei Sonnenaufgang
  description: ""
  triggers:
    - trigger: sun
      event: sunrise
      offset: "00:30:00"
  conditions: []
  actions:
    - action: cover.open_cover
      metadata: {}
      data: {}
      target:
        entity_id:
          - cover.rollade_buero_fabian
  mode: single
