- alias: Rollade rauf bei Sonnenaufgang
  description: ""
  triggers:
    - trigger: sun
      event: sunrise
      offset: "00:30:00"
  conditions: []
  actions:
    - action: cover.open_cover
      metadata: {}
      data: {}
      target:
        entity_id:
          - cover.rollade_buero_fabian
          - cover.rollade_buero_merja
          - cover.rollade_hwr
          - cover.rollade_kueche_links
          - cover.rollade_kueche_rechts
          - cover.rollade_speisekammer
          - cover.rollade_wohnzimmer_links
          - cover.rollade_wohnzimmer_rechts
  mode: single
