id: '1764188802719'
alias: Reset after 2 minutes
description: ''
triggers:
- trigger: state
  entity_id:
  - switch.water_cycling_pump
  to:
  - 'on'
conditions: []
actions:
- delay:
    hours: 0
    minutes: 2
    seconds: 0
    milliseconds: 0
- action: switch.turn_off
  metadata: {}
  data: {}
  target:
    entity_id: switch.water_cycling_pump
mode: single