alias: Water cycling pump reset
description: ""
triggers:
  - trigger: time_pattern
    minutes: "*"
conditions: []
actions:
  - action: input_number.decrement
    metadata: {}
    data: {}
    target:
      entity_id: input_number.water_cycling_pump_reset
mode: single
