- alias: Water cycling pump
  description: ""
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.presence_bad
      from: "off"
      to: "on"
  conditions:
  - condition: numeric_state
    entity_id: input_number.water_cycling_pump_reset
    below: 0
  actions:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.water_cycling_pump
    - delay:
        hours: 0
        minutes: 5
        seconds: 0
        milliseconds: 0
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.water_cycling_pump
    - action: input_number.set_value
      metadata: {}
      data:
        value: 360
      target:
        entity_id: input_number.water_cycling_pump_reset
  mode: single
