esphome:
  name: air-quality-0

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: sensair_background_calibrate
      then:
        - senseair.background_calibration: senseair_s
    - service: sensair_background_calibration_result
      then:
        - senseair.background_calibration_result: senseair_s

ota:
  password: !secret air_ota_password

# Create a switch for safe_mode in order to flash the device
# Solution from this thread:
# https://community.home-assistant.io/t/esphome-flashing-over-wifi-does-not-work/357352/1
switch:
  - platform: safe_mode
    name: "Flash Mode (Safe Mode)"
  - platform: gpio
    pin: 
      number: D7
    inverted: no
    id: pms_set

interval:
  - interval: 10s
    then:
      - switch.turn_on: pms_set
      - delay: 3s
      - switch.turn_off: pms_set

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart1
    
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart2
  
sensor:
  - platform: pmsx003
    type: PMS5003T
    uart_id: uart1
    pm_2_5:
      id: pm25
      name: "Particulate Matter <2.5µm Concentration"
  - platform: senseair
    id: senseair_s
    uart_id: uart2
    co2:
      id: co2
      name: "SenseAir CO2 Value"
    update_interval: 10s