esphome:
  name: water-heating
  friendly_name: Water Heating PV

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "/KB+xgAfPz+UrGmesUnxvhrWI9+BeZAbnybJBl2AjxY="

ota:
  - platform: esphome
    password: "4ec94af731a472c85ac87aebb022ab2d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    