esphome:
  name: rose

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret rose_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: adc
    pin: GPIO17
    name: "Rose Moisture sensor"
    id: "rose_moisture_sensor"
    update_interval: 1s
    unit_of_measurement: "V"
    filters:
    - median:
        window_size: 120
        send_every: 10
        send_first_at: 5
    accuracy_decimals: 2
