esphome:
  name: water-heater-pv-switch
  friendly_name: Water Heater PV Switch

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "y++os6TGHLK2WyX3iGdYkMcW+S445P7gnQsDDr22/Qs="

ota:
  - platform: esphome
    password: "4a53880ec156c96355eb019d61aa4a1c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water-Heater-Pv-Switch"
    password: "vRvSfvrEvGgu"

# Example configuration entry
switch:
  - platform: gpio
    pin: GPIO5
    name: "Powerr Usage Stage 1"
    inverted: true
  - platform: gpio
    pin: GPIO4
    name: "Powerr Usage Stage 2"
    inverted: true